apiVersion: apps/v1
kind: Deployment
metadata:
  name: cervejasms-deploy
  labels:
    app: cervejasms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cervejasms
  template:
    metadata:
      name: cervejasms-deploy
      labels:
        app: cervejasms
    spec:
      containers:
        - name: cervejasms-deploy
          image: leogloriainfnet/cervejas-ms:latest
          imagePullPolicy: Always
      restartPolicy: Always
      